markdown        : kramdown
kramdown        :
  entity_output : as_input # &mdash; is output as &mdash;
  smart_quotes  : [39, 39, 34, 34] # decimal for left/right single/double quotes
exclude         : [tools]
swc_blog        : "http://software-carpentry.org/feed.xml"
swc_contact     : "admin@software-carpentry.org"
swc_files       : "http://files.software-carpentry.org"
swc_github      : "http://github.com/swcarpentry"
swc_installer   : "http://files.software-carpentry.org/SWCarpentryInstaller.exe"
swc_lessons     : "http://software-carpentry.org/v5/novice"
swc_site        : "http://software-carpentry.org"
swc_twitter     : "http://twitter.com/swcarpentry"
swc_vm_url      : "https://docs.google.com/uc?id=0B4Kr6DYkzkQtd05FekRId05DLXM&amp;export=download"
