#------------------------------------------------------------
# Values for this workshop.
#------------------------------------------------------------

# More detailed instructions are available at:
# https://carpentries.github.io/workshop-template/customization/index.html

# Which carpentry is this ("swc", "dc", "lc", or "cp")?
# swc: Software Carpentry
#  dc: Data Carpentry
#  lc: Library Carpentry
#  cp: Carpentries (to use for instructor training for instance)
#  incubator: for workshops teaching a lesson in The Carpentries Incubator
# Note that for regular workshops, you should use:
#  https://github.com/carpentries/workshop-template
# and for instructor training events you should use:
#  https://github.com/carpentries/training-template
# When setting this field to "incubator", please uncomment the
# incubator_lesson_site, incubator_pre_survey, and incubator_post_survey
# lines further down this file and add the URL to the relevant lesson site.
carpentry: "swc"

# This option is currently only needed for
# Data Carpentry and Software Carpentry workshops.
# The value of the variable will be ignored for Library Carpentry
# workshops.
# Possible values are:
# dc-astronomy: for Data Carpentry Astronomy
# dc-ecology: for Data Carpentry Ecology
# dc-genomics: for Data Carpentry Genomics
# dc-socsci: for Data Carpentry Social Sciences
# dc-geospatial: for Data Carpentry Geospatial
# swc-inflammation: for Software Carpentry based on the inflammation dataset
# swc-gapminder: for Software Carpentry based on the Gapminder dataset
curriculum: "FIXME"

# If there is both an R and python official version of a curriculum
# (as listed on https://software-carpentry.org/lessons/ and
# https://datacarpentry.org/lessons/), change the
# value of the variable below ("flavor") to get the schedule and installation
# instructions updated accordingly (valid values are 'r' or 'python').
# Note: this is only for Data Carpentry and SWC at this time.
flavor: "FIXME"

# If the workshop will be a lesson pilot (for a new official lesson or
# a lesson in The Carpentries Incubator), set pilot to "true"
pilot: false

# Overall title for the Workshop.
# This variable is used to (optionally) add a title in the "jumbotron"
# (the grey box at the top of the page), and to the extra pages.
# Most workshops don't use extra pages. More information about extra
# pages are included in the README:
# https://github.com/carpentries/workshop-template#creating-extra-pages
title: "Workshop Title"

#------------------------------------------------------------
# Incubator workshop settings (only relevant for workshops teaching a lesson
# in The Carpentries Incubator).
#
# For an Incubator workshop, uncomment the line below and add the URL of the lesson site.
# incubator_lesson_site: "put the URL of the lesson being taught here"
#
# For an Incubator workshop, uncomment the line below and add the URL of your pre-workshop survey
# incubator_pre_survey: "put the URL of your pre-workshop survey here"
#
# For an Incubator workshop, uncomment the line below and add the URL of your post-workshop survey
# incubator_post_survey: "put the URL of your post-workshop survey here"
#
#------------------------------------------------------------

#------------------------------------------------------------
# Generic settings (should not need to change).
#------------------------------------------------------------

# This setting (kind) takes configurations from the styles
# template. Please do not modify this. If you are teaching 
# a custom set of lessons or a single lesson, use a custom 
# schedule.
kind: "workshop"

# Magic to make URLs resolve both locally and on GitHub.
# See https://help.github.com/articles/repository-metadata-on-github-pages/.
# Please don't change it: <USERNAME>/<PROJECT> is correct.
repository: <USERNAME>/<PROJECT>

# Email address, no mailto:
# (Don't change this -- the contact address for your workshop will be set
# in the index.md file)
email: "team@carpentries.org"

# Sites.
amy_site: "https://amy.carpentries.org"
carpentries_github: "https://github.com/carpentries"
carpentries_pages: "https://carpentries.github.io"
carpentries_site: "https://carpentries.org/"
dc_site: "https://datacarpentry.org"
example_repo: "https://github.com/carpentries/lesson-example"
example_site: "https://carpentries.github.io/lesson-example"
incubator: "https://github.com/carpentries-incubator/"
lc_site: "https://librarycarpentry.org/"
swc_github: "https://github.com/swcarpentry"
swc_pages: "https://swcarpentry.github.io"
swc_site: "https://software-carpentry.org"
template_repo: "https://github.com/carpentries/styles"
training_site: "https://carpentries.github.io/instructor-training"
workshop_repo: "https://github.com/carpentries/workshop-template"
workshop_site: "https://carpentries.github.io/workshop-template"
cc_by_human: "https://creativecommons.org/licenses/by/4.0/"

# Surveys.
pre_survey: "https://carpentries.typeform.com/to/wi32rS?slug="
post_survey: "https://carpentries.typeform.com/to/UgVdRQ?slug="

# Start time in minutes (0 to be clock-independent, 540 to show a start at 09:00 am).
start_time: 0

# Specify that things in the episodes collection should be output.
collections:
  episodes:
    output: true
    permalink: /:path/index.html
  extras:
    output: true
    permalink: /:path/index.html

# Set the default layout for things in the episodes collection.
defaults:
  - values:
      root: .
      layout: page
  - scope:
      path: ""
      type: episodes
    values:
      root: ..
      layout: episode
  - scope:
      path: ""
      type: extras
    values:
      root: ..
      layout: page

# Files and directories that are not to be copied.
exclude:
  - Makefile
  - bin/
  - .Rproj.user/
  - .vendor/
  - vendor/
  - .docker-vendor/

# Turn on built-in syntax highlighting.
highlighter: rouge
